# -*- coding: utf-8 -*-
#
# WDRT documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 12 10:32:32 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
# import shlex


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath("../"))
# print sys.path

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'matplotlib.sphinxext.plot_directive',
    'sphinx.ext.napoleon',
    'sphinxcontrib.googleanalytics'
]

googleanalytics_id = 'UA-97337554-1'


source_suffix = '.rst'

autodoc_member_order = 'groupwise'

# Include __init__ method documentation
autoclass_content = 'both'

master_doc = 'index'

project = u'WDRT'
copyright = u'2016, Sandia National Laboratories and The National Renewable Energy Laboratory'
author = u'Sandia National Laboratories and The National Renewable Energy Laboratory'

# The short X.Y version.
version = '1.0'
# The full version, including alpha/beta/rc tags.
release = '1.0'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

html_theme = 'sphinx_rtd_theme'

htmlhelp_basename = 'WDRTdoc'

html_static_path = ['_static']

latex_documents = [
    (master_doc, 'WDRT.tex', u'WDRT Documentation',
     u'SNL and NREL', 'manual'),
]

man_pages = [
    (master_doc, 'WDRT', u'WDRT Documentation',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'WDRT', u'WDRT Documentation',
     author, 'WDRT', 'One line description of project.',
     'Miscellaneous'),
]
